#!/usr/bin/env python

import sys
import curses

import text_editor

def main():
    if len(sys.argv) == 2:
        filename=str(sys.argv[1])
    elif len(sys.argv) == 1:
        filename = input("Please name your file: ")
    else:
        raise AttributeError
    view = curses.initscr()
    size = (view.getmaxyx()[0],view.getmaxyx()[1]-1)
    model = text_editor.WindowedLines(window_size=size)
    controller = text_editor.Controller(model=model, view=view)
    controller.run(filename)

if __name__ == "__main__":
    main()
