#!/usr/bin/env python

import sys
import curses
import pickle
import text_editor

def main():
    if len(sys.argv) == 2:
        filename=str(sys.argv[1])
    elif len(sys.argv) == 1:
        filename = None
        while not filename:
            filename = input("Please name your file: ")
    else:
        raise AttributeError
    window = curses.initscr()
    view = text_editor.View(window=window)
    
    model = text_editor.WindowedLines(window_size=(window.getmaxyx()[0], window.getmaxyx()[1]-1))
    with open('saved_dictionary.pkl', 'rb') as f:
        input_phoneme = text_editor.InputPhoneme(pickle.load(f))
    controller = text_editor.Controller(model=model, view=view, input_phoneme=input_phoneme, window=window)
    controller.run(filename)

if __name__ == "__main__":
    main()
